import os
import smtplib
import random
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Try to import the modern 2026 Google SDK
try:
    from google import genai
except ImportError:
    print("❌ Error: google-genai library not found. Check GitHub Actions logs.")
    raise

# --- CONFIGURATION ---
GEMINI_KEY = os.environ.get("AIzaSyBUlBeSiGmx5_nGW4AyIibRGF9xveB4Fp4")
BLOGGER_EMAIL = "karroumiabdo580.aipost@blogger.com"
SENDER_EMAIL = "karroumiabdo580@gmail.com" 
SENDER_PASSWORD = "arojzxofkobgtpdk" 

# Initialize Gemini Client
client = genai.Client(api_key=GEMINI_KEY)

topics = [
    "The Future of AI Agents in 2026",
    "How to Automate Your Business for Free",
    "Top 5 AI Tools for Content Creators",
    "Why 2026 is the Year of Personal AI"
]
target_keyword = random.choice(topics)

def generate_content(keyword):
    print(f"🤖 Gemini is writing about: {keyword}...")
    
    prompt = f"Write a professional, 1200-word viral blog post about '{keyword}' in clean HTML. Use H2 headers, bold text, and bullet points."
    
    # Using Gemini 2.0 Flash (Fastest and Free)
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=prompt
    )
    return response.text

def publish_post():
    try:
        print("🚀 Starting Automated Process...")
        blog_html = generate_content(target_keyword)
        
        # Generate a matching image using Pollinations (Free)
        img_url = f"https://image.pollinations.ai/prompt/futuristic_tech_{target_keyword.replace(' ','_')}?width=1080&height=720&nologo=true"
        
        full_body = f"""
        <div style="font-family: Arial, sans-serif; line-height: 1.8;">
            <img src="{img_url}" style="width:100%; border-radius:15px; margin-bottom: 20px;">
            {blog_html}
            <hr>
            <p style="text-align:center; color:#888;"><i>Post generated by AI FastTrack 2026 #end.</i></p>
        </div>
        """

        msg = MIMEMultipart()
        msg['Subject'] = target_keyword
        msg['From'] = SENDER_EMAIL
        msg['To'] = BLOGGER_EMAIL
        msg.attach(MIMEText(full_body, 'html'))
        
        print("📧 Logging into Gmail and sending...")
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, BLOGGER_EMAIL, msg.as_string())
        server.quit()
        
        print(f"✅ SUCCESS! Your blog post is live.")
        
    except Exception as e:
        print(f"❌ CRITICAL ERROR: {str(e)}")

if __name__ == "__main__":
    publish_post()
