import os
import smtplib
import random
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from google import genai

# --- 1. CONFIGURATION ---
GEMINI_KEY = os.environ.get("AIzaSyBUlBeSiGmx5_nGW4AyIibRGF9xveB4Fp4")
BLOGGER_EMAIL = "karroumiabdo580.aipost@blogger.com"
SENDER_EMAIL = "karroumiabdo580@gmail.com" 
SENDER_PASSWORD = "arojzxofkobgtpdk" 

client = genai.Client(api_key=GEMINI_KEY)

# --- 2. THE TOPICS ---
topics = [
    "How to build a 24/7 AI Sales Agent for $0 in 2026",
    "Gemini 1.5 Flash vs GPT-4o: Which is better for free automation?",
    "Top 10 Hidden AI tools that replaced my $500/month subscriptions",
    "How AI is changing the job market in 2026"
]
target_keyword = random.choice(topics)

# --- 3. GENERATE CONTENT ---
def generate_content(keyword):
    prompt = f"Write a 1,500-word viral tech blog post about '{keyword}' in clean HTML format. Use H2 headers, bullet points, and a professional tone."
    
    # FIXED MODEL NAME HERE
    response = client.models.generate_content(model="gemini-1.5-flash", contents=prompt)
    
    # Image Generation
    img_url = f"https://image.pollinations.ai/prompt/futuristic%20tech%20{keyword.replace(' ','%20')}?width=1080&height=720&nologo=true"
    
    html_body = f"""
    <div style="font-family: Arial, sans-serif; line-height: 1.8; color: #333;">
        <img src="{img_url}" style="width:100%; border-radius:15px; margin-bottom: 20px;">
        <div style="font-size: 16px;">
            {response.text}
        </div>
        <hr style="border: 0; border-top: 1px solid #eee; margin: 40px 0;">
        <p style="text-align: center; color: #888;"><i>Post generated by The AI FastTrack Engine #end.</i></p> 
    </div>
    """
    return html_body

def publish_post():
    print(f"🚀 Starting process for: {target_keyword}")
    try:
        content = generate_content(target_keyword)
        
        msg = MIMEMultipart()
        msg['Subject'] = target_keyword
        msg['From'] = SENDER_EMAIL
        msg['To'] = BLOGGER_EMAIL
        msg.attach(MIMEText(content, 'html'))
        
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, BLOGGER_EMAIL, msg.as_string())
        print(f"✅ SUCCESS! Post '{target_keyword}' is now live on Blogger.")
    except Exception as e:
        print(f"❌ ERROR: {e}")

if __name__ == "__main__":
    publish_post()
