import os
import smtplib
import random
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from google import genai

# --- CONFIGURATION ---
GEMINI_KEY = os.environ.get("AIzaSyBUlBeSiGmx5_nGW4AyIibRGF9xveB4Fp4")
BLOGGER_EMAIL = "karroumiabdo580.aipost@blogger.com"
SENDER_EMAIL = "karroumiabdo580@gmail.com" 
SENDER_PASSWORD = "arojzxofkobgtpdk" 

client = genai.Client(api_key=GEMINI_KEY)

# Use the 2026 stable model name
MODEL_NAME = "gemini-2.0-flash" 

topics = [
    "How to build a 24/7 AI Sales Agent for $0 in 2026",
    "Top 10 Hidden AI tools that replaced my $500/month subscriptions",
    "Why Gemini 2.0 is the best AI for automation in 2026"
]
target_keyword = random.choice(topics)

def generate_content(keyword):
    print(f"🤖 Calling AI model: {MODEL_NAME}...")
    prompt = f"Write a 1200 word viral blog post about {keyword} in clean HTML format with H2 headers."
    
    # Generate content using the new model name
    response = client.models.generate_content(model=MODEL_NAME, contents=prompt)
    
    img_url = f"https://image.pollinations.ai/prompt/tech_{keyword.replace(' ','_')}?width=1080&height=720&nologo=true"
    
    html_body = f"""
    <div style="font-family: Arial, sans-serif; line-height: 1.8;">
        <img src="{img_url}" style="width:100%; border-radius:15px; margin-bottom: 20px;">
        {response.text}
        <p style="text-align: center; color: #888;"><i>Generated by AI FastTrack #end.</i></p>
    </div>
    """
    return html_body

def publish_post():
    try:
        content = generate_content(target_keyword)
        print("📧 Content generated. Sending to Blogger...")
        
        msg = MIMEMultipart()
        msg['Subject'] = target_keyword
        msg['From'] = SENDER_EMAIL
        msg['To'] = BLOGGER_EMAIL
        msg.attach(MIMEText(content, 'html'))
        
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, BLOGGER_EMAIL, msg.as_string())
        server.quit()
        
        print(f"✅ SUCCESS! Check your blog now for: {target_keyword}")
        
    except Exception as e:
        print(f"❌ ERROR: {str(e)}")

if __name__ == "__main__":
    publish_post()
